/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Conexao;
import dao.PlaylistDAO;
import java.sql.Connection;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Usuario;
import model.Video;
import controller.PlaylistController;

public class Addplaylist extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Addplaylist.class.getName());
    private Usuario usuarioLogado;
    private Video video;
    private PlaylistController playlistController = new PlaylistController();

    public Addplaylist() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public Addplaylist(Usuario usuarioLogado, Video video) {
        initComponents();
        this.usuarioLogado = usuarioLogado;
        this.video = video;
        setLocationRelativeTo(null);
        carregarPlaylists();
    }

    public Addplaylist(JLabel jLabel1, JComboBox<String> playlist_boxselect, JButton voltar_btn) {
        this.jLabel1 = jLabel1;
        this.playlist_boxselect = playlist_boxselect;
        this.adicionar_btn = voltar_btn;
    }
    
   private void carregarPlaylists() {
        try (Connection conn = new Conexao().getConnection()) {
            PlaylistDAO dao = new PlaylistDAO(conn);
            List<String> playlists = dao.listarPlaylistsDoUsuario(usuarioLogado.getId());

            playlist_boxselect.removeAllItems();

            for (String nome : playlists) {
                playlist_boxselect.addItem(nome);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar playlists: " + e.getMessage());
        }
    }

    private void adicionarNaPlaylist() {
        String nomePlaylist = (String) playlist_boxselect.getSelectedItem();

        if (nomePlaylist == null || nomePlaylist.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione uma playlist.");
            return;
        }

        if (video == null) {
            JOptionPane.showMessageDialog(this, "Vídeo não encontrado.");
            return;
        }

        JOptionPane.showMessageDialog(this, "Playlist: " + nomePlaylist + " | ID do vídeo: " + video.getId());

        try (Connection conn = new Conexao().getConnection()) {
            PlaylistDAO dao = new PlaylistDAO(conn);
            int idPlaylist = dao.buscarIdPlaylist(nomePlaylist, usuarioLogado.getId());
            dao.adicionarVideoNaPlaylist(idPlaylist, video.getId());

            JOptionPane.showMessageDialog(this, "Filme adicionado à playlist.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar na playlist: " + e.getMessage());
        }
    }

    public static Logger getLogger() {
        return logger;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JComboBox<String> getPlaylist_boxselect() {
        return playlist_boxselect;
    }

    public JButton getVoltar_btn() {
        return adicionar_btn;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setPlaylist_boxselect(JComboBox<String> playlist_boxselect) {
        this.playlist_boxselect = playlist_boxselect;
    }

    public void setVoltar_btn(JButton voltar_btn) {
        this.adicionar_btn = voltar_btn;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        playlist_boxselect = new javax.swing.JComboBox<>();
        adicionar_btn = new javax.swing.JButton();
        voltar_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Selecione a playlist");

        playlist_boxselect.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        playlist_boxselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nome playlist" }));
        playlist_boxselect.addActionListener(this::playlist_boxselectActionPerformed);

        adicionar_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        adicionar_btn.setText("Adicionar");
        adicionar_btn.addActionListener(this::adicionar_btnActionPerformed);

        voltar_btn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        voltar_btn1.setText("Voltar");
        voltar_btn1.addActionListener(this::voltar_btn1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(playlist_boxselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(adicionar_btn)
                        .addGap(352, 352, 352))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(391, Short.MAX_VALUE)
                    .addComponent(voltar_btn1)
                    .addGap(373, 373, 373)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(127, 127, 127)
                .addComponent(playlist_boxselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(adicionar_btn)
                .addGap(145, 145, 145))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(564, Short.MAX_VALUE)
                    .addComponent(voltar_btn1)
                    .addGap(95, 95, 95)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionar_btnActionPerformed
        // TODO add your handling code here:
        String nomePlaylist = (String) playlist_boxselect.getSelectedItem();
        String mensagem = playlistController.adicionarVideoNaPlaylist(nomePlaylist, usuarioLogado, video);
        JOptionPane.showMessageDialog(this, mensagem);
    }//GEN-LAST:event_adicionar_btnActionPerformed

    private void playlist_boxselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlist_boxselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playlist_boxselectActionPerformed

    private void voltar_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_btn1ActionPerformed
        // TODO add your handling code here:
        Card tela = new Card(video, usuarioLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltar_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Addplaylist().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> playlist_boxselect;
    private javax.swing.JButton voltar_btn1;
    // End of variables declaration//GEN-END:variables
}
