/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import controller.UsuarioController;

/**
 *
 * @author ArturGuimaraesdeSouz
 */
public class Cadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastro.class.getName());

    /**
     * Creates new form Cadastro
     */
    private UsuarioController controller;
    
    public Cadastro() {
        initComponents();
        controller = new UsuarioController();
    }

    public Cadastro(JScrollPane jScrollPane1, JScrollPane jScrollPane2, JScrollPane jScrollPane3, JTextArea nome_input, JLabel nome_lbl, JButton salvar_btn, JTextArea senha_input, JLabel senha_lbl, JTextArea usuario_input, JLabel usuario_lbl) {
        this.jScrollPane1 = jScrollPane1;
        this.jScrollPane2 = jScrollPane2;
        this.jScrollPane3 = jScrollPane3;
        this.nome_input = nome_input;
        this.nome_lbl = nome_lbl;
        this.salvar_btn = salvar_btn;
        this.senha_input = senha_input;
        this.senha_lbl = senha_lbl;
        this.usuario_input = usuario_input;
        this.usuario_lbl = usuario_lbl;
    }

    public static Logger getLogger() {
        return logger;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public JTextArea getNome_input() {
        return nome_input;
    }

    public JLabel getNome_lbl() {
        return nome_lbl;
    }

    public JButton getSalvar_btn() {
        return salvar_btn;
    }

    public JTextArea getSenha_input() {
        return senha_input;
    }

    public JLabel getSenha_lbl() {
        return senha_lbl;
    }

    public JTextArea getUsuario_input() {
        return usuario_input;
    }

    public JLabel getUsuario_lbl() {
        return usuario_lbl;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public void setNome_input(JTextArea nome_input) {
        this.nome_input = nome_input;
    }

    public void setNome_lbl(JLabel nome_lbl) {
        this.nome_lbl = nome_lbl;
    }

    public void setSalvar_btn(JButton salvar_btn) {
        this.salvar_btn = salvar_btn;
    }

    public void setSenha_input(JTextArea senha_input) {
        this.senha_input = senha_input;
    }

    public void setSenha_lbl(JLabel senha_lbl) {
        this.senha_lbl = senha_lbl;
    }

    public void setUsuario_input(JTextArea usuario_input) {
        this.usuario_input = usuario_input;
    }

    public void setUsuario_lbl(JLabel usuario_lbl) {
        this.usuario_lbl = usuario_lbl;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        senha_input = new javax.swing.JTextArea();
        senha_lbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usuario_input = new javax.swing.JTextArea();
        salvar_btn = new javax.swing.JButton();
        usuario_lbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        nome_input = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nome_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nome_lbl.setText("Nome:");

        senha_input.setColumns(20);
        senha_input.setRows(5);
        jScrollPane1.setViewportView(senha_input);

        senha_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        senha_lbl.setText("Senha:");

        usuario_input.setColumns(20);
        usuario_input.setRows(5);
        jScrollPane2.setViewportView(usuario_input);

        salvar_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        salvar_btn.setText("SALVAR");
        salvar_btn.addActionListener(this::salvar_btnActionPerformed);

        usuario_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        usuario_lbl.setText("Usuário:");

        nome_input.setColumns(20);
        nome_input.setRows(5);
        jScrollPane3.setViewportView(nome_input);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senha_lbl)
                    .addComponent(nome_lbl)
                    .addComponent(usuario_lbl))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salvar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(nome_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(usuario_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senha_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(76, 76, 76)
                .addComponent(salvar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_btnActionPerformed
        // TODO add your handling code here:
        controller.cadastrar(this);
    }//GEN-LAST:event_salvar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Cadastro().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea nome_input;
    private javax.swing.JLabel nome_lbl;
    private javax.swing.JButton salvar_btn;
    private javax.swing.JTextArea senha_input;
    private javax.swing.JLabel senha_lbl;
    private javax.swing.JTextArea usuario_input;
    private javax.swing.JLabel usuario_lbl;
    // End of variables declaration//GEN-END:variables
}
