/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import dao.Conexao;
import dao.PlaylistDAO;
import java.sql.Connection;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Playlist;
import model.Usuario;
import model.Video;
import dao.Conexao;
import dao.CurtidaDAO;
import java.sql.Connection;
import controller.CurtidaController;

/**
 *
 * @author ArturGuimaraesdeSouz
 */
public class Card extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Card.class.getName());
    private Video video;
    private Usuario usuarioLogado;
    private CurtidaController curtidaController = new CurtidaController();
    
    /**
     * Creates new form Card
     */
    
    public Card() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public Card(JLabel ano_lbl, JButton curtir_btn, JLabel descricao_lbl, JButton descurtir_btn, JButton favoritar_btn, JPanel filme_panel, JLabel genero_lbl, JPanel jPanel1, JLabel nomeFilme_lbl) {
        this.ano_lbl = ano_lbl;
        this.curtir_btn = curtir_btn;
        this.descricao_lbl = descricao_lbl;
        this.descurtir_btn = descurtir_btn;
        this.addPlaylist_btn = favoritar_btn;
        this.filme_panel = filme_panel;
        this.genero_lbl = genero_lbl;
        this.jPanel1 = jPanel1;
        this.nomeFilme_lbl = nomeFilme_lbl;
    }

    public Card(Video video, Usuario usuarioLogado) {
        initComponents();
        setLocationRelativeTo(null);
        this.video = video;
        this.usuarioLogado = usuarioLogado;

        if (video != null) {
            nomeFilme_lbl.setText(video.getTitulo());
            genero_lbl.setText(video.getGenero());
            descricao_lbl.setText(video.getDescricao());
            ano_lbl.setText(String.valueOf(video.getAno()));
        }
    }


    public static Logger getLogger() {
        return logger;
    }

    public JLabel getAno_lbl() {
        return ano_lbl;
    }

    public JButton getCurtir_btn() {
        return curtir_btn;
    }

    public JLabel getDescricao_lbl() {
        return descricao_lbl;
    }

    public JButton getDescurtir_btn() {
        return descurtir_btn;
    }

    public JButton getFavoritar_btn() {
        return addPlaylist_btn;
    }

    public JPanel getFilme_panel() {
        return filme_panel;
    }

    public JLabel getGenero_lbl() {
        return genero_lbl;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JLabel getNomeFilme_lbl() {
        return nomeFilme_lbl;
    }

    public void setAno_lbl(JLabel ano_lbl) {
        this.ano_lbl = ano_lbl;
    }

    public void setCurtir_btn(JButton curtir_btn) {
        this.curtir_btn = curtir_btn;
    }

    public void setDescricao_lbl(JLabel descricao_lbl) {
        this.descricao_lbl = descricao_lbl;
    }

    public void setDescurtir_btn(JButton descurtir_btn) {
        this.descurtir_btn = descurtir_btn;
    }

    public void setFavoritar_btn(JButton favoritar_btn) {
        this.addPlaylist_btn = favoritar_btn;
    }

    public void setFilme_panel(JPanel filme_panel) {
        this.filme_panel = filme_panel;
    }

    public void setGenero_lbl(JLabel genero_lbl) {
        this.genero_lbl = genero_lbl;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public void setNomeFilme_lbl(JLabel nomeFilme_lbl) {
        this.nomeFilme_lbl = nomeFilme_lbl;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filme_panel = new javax.swing.JPanel();
        nomeFilme_lbl = new javax.swing.JLabel();
        genero_lbl = new javax.swing.JLabel();
        descricao_lbl = new javax.swing.JLabel();
        ano_lbl = new javax.swing.JLabel();
        curtir_btn = new javax.swing.JButton();
        descurtir_btn = new javax.swing.JButton();
        addPlaylist_btn = new javax.swing.JButton();
        voltar_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        nomeFilme_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomeFilme_lbl.setText("NOME FILME");

        genero_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        genero_lbl.setText("Genero");

        descricao_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descricao_lbl.setText("Descricao");

        ano_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ano_lbl.setText("ano");

        curtir_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        curtir_btn.setText("Curtir");
        curtir_btn.addActionListener(this::curtir_btnActionPerformed);

        descurtir_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        descurtir_btn.setText("Descurtir");
        descurtir_btn.addActionListener(this::descurtir_btnActionPerformed);

        addPlaylist_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addPlaylist_btn.setText("Add a playlist");
        addPlaylist_btn.addActionListener(this::addPlaylist_btnActionPerformed);

        javax.swing.GroupLayout filme_panelLayout = new javax.swing.GroupLayout(filme_panel);
        filme_panel.setLayout(filme_panelLayout);
        filme_panelLayout.setHorizontalGroup(
            filme_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filme_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filme_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filme_panelLayout.createSequentialGroup()
                        .addGroup(filme_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genero_lbl)
                            .addComponent(descricao_lbl)
                            .addGroup(filme_panelLayout.createSequentialGroup()
                                .addComponent(nomeFilme_lbl)
                                .addGap(18, 18, 18)
                                .addComponent(ano_lbl)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(filme_panelLayout.createSequentialGroup()
                        .addComponent(curtir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(descurtir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(addPlaylist_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        filme_panelLayout.setVerticalGroup(
            filme_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filme_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filme_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFilme_lbl)
                    .addComponent(ano_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genero_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descricao_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(filme_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curtir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descurtir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPlaylist_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        voltar_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        voltar_btn.setText("Voltar");
        voltar_btn.addActionListener(this::voltar_btnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filme_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(voltar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(filme_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(voltar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void curtir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curtir_btnActionPerformed
        // TODO add your handling code here:
            String mensagem = curtidaController.curtir(usuarioLogado, video);
            JOptionPane.showMessageDialog(this, mensagem);
    
    }//GEN-LAST:event_curtir_btnActionPerformed

    private void descurtir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descurtir_btnActionPerformed
        // TODO add your handling code here:
            String mensagem = curtidaController.descurtir(usuarioLogado, video);
            JOptionPane.showMessageDialog(this, mensagem);
    }//GEN-LAST:event_descurtir_btnActionPerformed

    private void addPlaylist_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlaylist_btnActionPerformed
        // TODO add your handling code here:
        Addplaylist tela = new Addplaylist(usuarioLogado, video);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addPlaylist_btnActionPerformed

    private void voltar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_btnActionPerformed
        // TODO add your handling code here:
        TelaPrincipal telaPrincipal = new TelaPrincipal(usuarioLogado);
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Card().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlaylist_btn;
    private javax.swing.JLabel ano_lbl;
    private javax.swing.JButton curtir_btn;
    private javax.swing.JLabel descricao_lbl;
    private javax.swing.JButton descurtir_btn;
    private javax.swing.JPanel filme_panel;
    private javax.swing.JLabel genero_lbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeFilme_lbl;
    private javax.swing.JButton voltar_btn;
    // End of variables declaration//GEN-END:variables
}
