/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UsuarioController;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author ArturGuimaraesdeSouz
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    private UsuarioController controller;
    
    public Login() {
        initComponents();
        controller = new UsuarioController();
        setLocationRelativeTo(null);
    }

    
    
    public Login(JButton cadastrar_btn, JButton entrar_btn, JScrollPane jScrollPane1, JScrollPane jScrollPane2, JTextArea senha_input, JLabel senha_lbl, JTextArea usuario_input, JLabel usuario_lbl) {
        this.cadastrar_btn = cadastrar_btn;
        this.entrar_btn = entrar_btn;
        this.jScrollPane1 = jScrollPane1;
        this.jScrollPane2 = jScrollPane2;
        this.senha_input = senha_input;
        this.senha_lbl = senha_lbl;
        this.usuario_input = usuario_input;
        this.usuario_lbl = usuario_lbl;
    }

    public static Logger getLogger() {
        return logger;
    }

    public JButton getCadastrar_btn() {
        return cadastrar_btn;
    }

    public JButton getEntrar_btn() {
        return entrar_btn;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JTextArea getSenha_input() {
        return senha_input;
    }

    public JLabel getSenha_lbl() {
        return senha_lbl;
    }

    public JTextArea getUsuario_input() {
        return usuario_input;
    }

    public JLabel getUsuario_lbl() {
        return usuario_lbl;
    }

    public void setCadastrar_btn(JButton cadastrar_btn) {
        this.cadastrar_btn = cadastrar_btn;
    }

    public void setEntrar_btn(JButton entrar_btn) {
        this.entrar_btn = entrar_btn;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public void setSenha_input(JTextArea senha_input) {
        this.senha_input = senha_input;
    }

    public void setSenha_lbl(JLabel senha_lbl) {
        this.senha_lbl = senha_lbl;
    }

    public void setUsuario_input(JTextArea usuario_input) {
        this.usuario_input = usuario_input;
    }

    public void setUsuario_lbl(JLabel usuario_lbl) {
        this.usuario_lbl = usuario_lbl;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        senha_input = new javax.swing.JTextArea();
        senha_lbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usuario_input = new javax.swing.JTextArea();
        cadastrar_btn = new javax.swing.JButton();
        entrar_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuario_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        usuario_lbl.setText("Usuário:");

        senha_input.setColumns(20);
        senha_input.setRows(5);
        jScrollPane1.setViewportView(senha_input);

        senha_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        senha_lbl.setText("Senha:");

        usuario_input.setColumns(20);
        usuario_input.setRows(5);
        jScrollPane2.setViewportView(usuario_input);

        cadastrar_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cadastrar_btn.setText("CADASTRAR");
        cadastrar_btn.addActionListener(this::cadastrar_btnActionPerformed);

        entrar_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        entrar_btn.setText("ENTRAR");
        entrar_btn.addActionListener(this::entrar_btnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Bem vindo ao FEITv!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senha_lbl)
                    .addComponent(usuario_lbl))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entrar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastrar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(299, 299, 299))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(239, 239, 239))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(usuario_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senha_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(entrar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_btnActionPerformed
        // TODO add your handling code here:
        Cadastro telaCadastro = new Cadastro();
        telaCadastro.setLocationRelativeTo(null);
        telaCadastro.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cadastrar_btnActionPerformed

    private void entrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar_btnActionPerformed
        // TODO add your handling code here:
        controller.login(this);
    }//GEN-LAST:event_entrar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_btn;
    private javax.swing.JButton entrar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea senha_input;
    private javax.swing.JLabel senha_lbl;
    private javax.swing.JTextArea usuario_input;
    private javax.swing.JLabel usuario_lbl;
    // End of variables declaration//GEN-END:variables
}
