/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import dao.Conexao;
import dao.PlaylistDAO;
import java.sql.Connection;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import model.Usuario;
import model.Video;
import controller.PlaylistController;

/**
 *
 * @author ArturGuimaraesdeSouz
 */
public class Playlist extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Playlist.class.getName());
    private Usuario usuarioLogado;
    private String nomePlaylist;
    private List<Video> videosDaPlaylist;
    private PlaylistController playlistController = new PlaylistController();

    public Playlist() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public Playlist(Usuario usuarioLogado, String nomePlaylist) {
        initComponents();
        this.usuarioLogado = usuarioLogado;
        this.nomePlaylist = nomePlaylist;
        setLocationRelativeTo(null);

        nomePlaylist_lbl.setText(nomePlaylist);
        carregarVideosDaPlaylist();
    }

    public Playlist(JPanel jPanel1, JLabel nomePlaylist_lbl) {
        this.jPanel1 = jPanel1;
        this.nomePlaylist_lbl = nomePlaylist_lbl;
    }
    
    private void carregarVideosDaPlaylist() {
    limparPaineis();

        videosDaPlaylist = playlistController.listarVideosDaPlaylist(nomePlaylist, usuarioLogado);

        if (videosDaPlaylist.size() > 0) {
            nomeFilme_lbl.setText(videosDaPlaylist.get(0).getTitulo());
            genero_lbl.setText(videosDaPlaylist.get(0).getGenero());
            descricao_lbl.setText(videosDaPlaylist.get(0).getDescricao());
            ano_lbl.setText(String.valueOf(videosDaPlaylist.get(0).getAno()));
            filme_panel.setVisible(true);
        }

        if (videosDaPlaylist.size() > 1) {
            nomeFilme_lbl1.setText(videosDaPlaylist.get(1).getTitulo());
            genero_lbl1.setText(videosDaPlaylist.get(1).getGenero());
            descricao_lbl1.setText(videosDaPlaylist.get(1).getDescricao());
            ano_lbl1.setText(String.valueOf(videosDaPlaylist.get(1).getAno()));
            filme_panel1.setVisible(true);
        }

        if (videosDaPlaylist.size() > 2) {
            nomeFilme_lbl2.setText(videosDaPlaylist.get(2).getTitulo());
            genero_lbl2.setText(videosDaPlaylist.get(2).getGenero());
            descricao_lbl2.setText(videosDaPlaylist.get(2).getDescricao());
            ano_lbl2.setText(String.valueOf(videosDaPlaylist.get(2).getAno()));
            filme_panel2.setVisible(true);
        }
    }
        
    private void removerVideoPorIndice(int indice) {
        if (videosDaPlaylist == null || indice < 0 || indice >= videosDaPlaylist.size()) {
            JOptionPane.showMessageDialog(this, "Vídeo não encontrado.");
            return;
        }

        int idVideo = videosDaPlaylist.get(indice).getId();
        String mensagem = playlistController.removerVideoDaPlaylist(nomePlaylist, usuarioLogado, idVideo);
        JOptionPane.showMessageDialog(this, mensagem);
        carregarVideosDaPlaylist();
        }
     
    private void limparPaineis() {
        filme_panel.setVisible(false);
        filme_panel1.setVisible(false);
        filme_panel2.setVisible(false);

        nomeFilme_lbl.setText("");
        genero_lbl.setText("");
        descricao_lbl.setText("");
        ano_lbl.setText("");

        nomeFilme_lbl1.setText("");
        genero_lbl1.setText("");
        descricao_lbl1.setText("");
        ano_lbl1.setText("");

        nomeFilme_lbl2.setText("");
        genero_lbl2.setText("");
        descricao_lbl2.setText("");
        ano_lbl2.setText("");
      }

    public static Logger getLogger() {
        return logger;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JLabel getNomePlaylist_lbl() {
        return nomePlaylist_lbl;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public void setNomePlaylist_lbl(JLabel nomePlaylist_lbl) {
        this.nomePlaylist_lbl = nomePlaylist_lbl;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomePlaylist_lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        voltar_btn = new javax.swing.JButton();
        filme_panel = new javax.swing.JPanel();
        nomeFilme_lbl = new javax.swing.JLabel();
        genero_lbl = new javax.swing.JLabel();
        descricao_lbl = new javax.swing.JLabel();
        ano_lbl = new javax.swing.JLabel();
        apagar_btn = new javax.swing.JButton();
        filme_panel1 = new javax.swing.JPanel();
        nomeFilme_lbl1 = new javax.swing.JLabel();
        genero_lbl1 = new javax.swing.JLabel();
        descricao_lbl1 = new javax.swing.JLabel();
        ano_lbl1 = new javax.swing.JLabel();
        apagar_btn1 = new javax.swing.JButton();
        filme_panel2 = new javax.swing.JPanel();
        nomeFilme_lbl2 = new javax.swing.JLabel();
        genero_lbl2 = new javax.swing.JLabel();
        descricao_lbl2 = new javax.swing.JLabel();
        ano_lbl2 = new javax.swing.JLabel();
        apagar_btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomePlaylist_lbl.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        nomePlaylist_lbl.setText("Nome playlist");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        voltar_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        voltar_btn.setText("Voltar");
        voltar_btn.addActionListener(this::voltar_btnActionPerformed);

        nomeFilme_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomeFilme_lbl.setText("NOME FILME");

        genero_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        genero_lbl.setText("Genero");

        descricao_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descricao_lbl.setText("Descricao");

        ano_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ano_lbl.setText("ano");

        apagar_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apagar_btn.setText("Apagar");
        apagar_btn.addActionListener(this::apagar_btnActionPerformed);

        javax.swing.GroupLayout filme_panelLayout = new javax.swing.GroupLayout(filme_panel);
        filme_panel.setLayout(filme_panelLayout);
        filme_panelLayout.setHorizontalGroup(
            filme_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filme_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filme_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genero_lbl)
                    .addComponent(descricao_lbl)
                    .addGroup(filme_panelLayout.createSequentialGroup()
                        .addComponent(nomeFilme_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(ano_lbl)))
                .addContainerGap(379, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filme_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(apagar_btn)
                .addGap(40, 40, 40))
        );
        filme_panelLayout.setVerticalGroup(
            filme_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filme_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filme_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFilme_lbl)
                    .addComponent(ano_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genero_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descricao_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(apagar_btn)
                .addContainerGap())
        );

        nomeFilme_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomeFilme_lbl1.setText("NOME FILME");

        genero_lbl1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        genero_lbl1.setText("Genero");

        descricao_lbl1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descricao_lbl1.setText("Descricao");

        ano_lbl1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ano_lbl1.setText("ano");

        apagar_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apagar_btn1.setText("Apagar");
        apagar_btn1.addActionListener(this::apagar_btn1ActionPerformed);

        javax.swing.GroupLayout filme_panel1Layout = new javax.swing.GroupLayout(filme_panel1);
        filme_panel1.setLayout(filme_panel1Layout);
        filme_panel1Layout.setHorizontalGroup(
            filme_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filme_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filme_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genero_lbl1)
                    .addComponent(descricao_lbl1)
                    .addGroup(filme_panel1Layout.createSequentialGroup()
                        .addComponent(nomeFilme_lbl1)
                        .addGap(18, 18, 18)
                        .addComponent(ano_lbl1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filme_panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(apagar_btn1)
                .addGap(41, 41, 41))
        );
        filme_panel1Layout.setVerticalGroup(
            filme_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filme_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filme_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFilme_lbl1)
                    .addComponent(ano_lbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genero_lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descricao_lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(apagar_btn1)
                .addContainerGap())
        );

        nomeFilme_lbl2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomeFilme_lbl2.setText("NOME FILME");

        genero_lbl2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        genero_lbl2.setText("Genero");

        descricao_lbl2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descricao_lbl2.setText("Descricao");

        ano_lbl2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ano_lbl2.setText("ano");

        apagar_btn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apagar_btn2.setText("Apagar");
        apagar_btn2.addActionListener(this::apagar_btn2ActionPerformed);

        javax.swing.GroupLayout filme_panel2Layout = new javax.swing.GroupLayout(filme_panel2);
        filme_panel2.setLayout(filme_panel2Layout);
        filme_panel2Layout.setHorizontalGroup(
            filme_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filme_panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filme_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filme_panel2Layout.createSequentialGroup()
                        .addGroup(filme_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genero_lbl2)
                            .addGroup(filme_panel2Layout.createSequentialGroup()
                                .addComponent(nomeFilme_lbl2)
                                .addGap(18, 18, 18)
                                .addComponent(ano_lbl2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(filme_panel2Layout.createSequentialGroup()
                        .addComponent(descricao_lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(apagar_btn2)
                        .addGap(44, 44, 44))))
        );
        filme_panel2Layout.setVerticalGroup(
            filme_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filme_panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filme_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFilme_lbl2)
                    .addComponent(ano_lbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genero_lbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descricao_lbl2)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filme_panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(apagar_btn2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(voltar_btn)
                .addGap(349, 349, 349))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filme_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filme_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filme_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(filme_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filme_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filme_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(voltar_btn)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(nomePlaylist_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(nomePlaylist_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_btnActionPerformed
        // TODO add your handling code here:
        SuaPlaylist tela = new SuaPlaylist(usuarioLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltar_btnActionPerformed

    private void apagar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagar_btnActionPerformed
        // TODO add your handling code here:
         removerVideoPorIndice(0);
    }//GEN-LAST:event_apagar_btnActionPerformed

    private void apagar_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagar_btn1ActionPerformed
        // TODO add your handling code here:
        removerVideoPorIndice(1);
    }//GEN-LAST:event_apagar_btn1ActionPerformed

    private void apagar_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagar_btn2ActionPerformed
        // TODO add your handling code here:
        removerVideoPorIndice(2);
    }//GEN-LAST:event_apagar_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Playlist().setVisible(true));
//    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ano_lbl;
    private javax.swing.JLabel ano_lbl1;
    private javax.swing.JLabel ano_lbl2;
    private javax.swing.JButton apagar_btn;
    private javax.swing.JButton apagar_btn1;
    private javax.swing.JButton apagar_btn2;
    private javax.swing.JLabel descricao_lbl;
    private javax.swing.JLabel descricao_lbl1;
    private javax.swing.JLabel descricao_lbl2;
    private javax.swing.JPanel filme_panel;
    private javax.swing.JPanel filme_panel1;
    private javax.swing.JPanel filme_panel2;
    private javax.swing.JLabel genero_lbl;
    private javax.swing.JLabel genero_lbl1;
    private javax.swing.JLabel genero_lbl2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeFilme_lbl;
    private javax.swing.JLabel nomeFilme_lbl1;
    private javax.swing.JLabel nomeFilme_lbl2;
    private javax.swing.JLabel nomePlaylist_lbl;
    private javax.swing.JButton voltar_btn;
    // End of variables declaration//GEN-END:variables
}
