/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Conexao;
import dao.VideoDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import model.Usuario;
import model.Video;
import controller.VideoController;

/**
 *
 * @author ArturGuimaraesdeSouz
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());
    private Usuario usuarioLogado;
    private VideoController videoController = new VideoController();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        configurarBusca();
        setLocationRelativeTo(null);
    }

    public TelaPrincipal(JLabel ano_lbl, JLabel descricao_lbl, JPanel filme_panel, JLabel genero_lbl, JLabel jLabel2, JPanel jPanel1, JScrollPane jScrollPane1, JLabel nomeFilme_lbl, JLabel nomeUsuario_lbl, JLabel ola_lbl, JTextArea pesquisa_txt) {
        this.jLabel2 = jLabel2;
        this.jPanel1 = jPanel1;
        this.jScrollPane1 = jScrollPane1;
        this.nomeUsuario_lbl = nomeUsuario_lbl;
        this.ola_lbl = ola_lbl;
        this.pesquisa_txt = pesquisa_txt;
    }

    public static Logger getLogger() {
        return logger;
    }

     public TelaPrincipal(Usuario usuarioLogado) {
        initComponents();
        this.usuarioLogado = usuarioLogado;
        configurarBusca();
        setLocationRelativeTo(null);

        if (usuarioLogado != null) {
            nomeUsuario_lbl.setText(usuarioLogado.getNome());
        } else {
            nomeUsuario_lbl.setText("Usuário");
        }
    }
    
       private void configurarBusca() {
        pesquisa_txt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    e.consume();
                    buscarVideo();
                }
            }
        });
    }

    private void buscarVideo() {
        String nomePesquisado = pesquisa_txt.getText().replace("\n", "").replace("\r", "").trim();

        if (nomePesquisado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o nome de um filme para pesquisar.");
            return;
        }

        try (Connection conn = new Conexao().getConnection()) {
            VideoDAO dao = new VideoDAO(conn);
            Video video = dao.buscarPorNome(nomePesquisado);

            if (video != null) {
                Card telaCard = new Card(video, usuarioLogado);
                telaCard.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Filme não encontrado.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar vídeo: " + e.getMessage());
        }
    }


    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getNomeUsuario_lbl() {
        return nomeUsuario_lbl;
    }

    public JLabel getOla_lbl() {
        return ola_lbl;
    }

    public JTextArea getPesquisa_txt() {
        return pesquisa_txt;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }
    
    public void setNomeUsuario_lbl(JLabel nomeUsuario_lbl) {
        this.nomeUsuario_lbl = nomeUsuario_lbl;
    }

    public void setOla_lbl(JLabel ola_lbl) {
        this.ola_lbl = ola_lbl;
    }

    public void setPesquisa_txt(JTextArea pesquisa_txt) {
        this.pesquisa_txt = pesquisa_txt;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ola_lbl = new javax.swing.JLabel();
        nomeUsuario_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pesquisa_txt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        checarPlaylists_btn = new javax.swing.JButton();
        criarPlaylist_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ola_lbl.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        ola_lbl.setText("Olá,");

        nomeUsuario_lbl.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        nomeUsuario_lbl.setText("NOME");

        pesquisa_txt.setColumns(20);
        pesquisa_txt.setRows(5);
        jScrollPane1.setViewportView(pesquisa_txt);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Procurar:");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        checarPlaylists_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        checarPlaylists_btn.setText("Ver playlists");
        checarPlaylists_btn.addActionListener(this::checarPlaylists_btnActionPerformed);

        criarPlaylist_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        criarPlaylist_btn.setText("Criar playlist");
        criarPlaylist_btn.addActionListener(this::criarPlaylist_btnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Acesse filmes e series e os organize em playlists!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checarPlaylists_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(criarPlaylist_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(criarPlaylist_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checarPlaylists_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ola_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(nomeUsuario_lbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ola_lbl)
                            .addComponent(nomeUsuario_lbl))
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checarPlaylists_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checarPlaylists_btnActionPerformed
        // TODO add your handling code here:
        SuaPlaylist tela = new SuaPlaylist(usuarioLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checarPlaylists_btnActionPerformed

    private void criarPlaylist_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarPlaylist_btnActionPerformed
        // TODO add your handling code here:
        Criarplaylist tela = new Criarplaylist(usuarioLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_criarPlaylist_btnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checarPlaylists_btn;
    private javax.swing.JButton criarPlaylist_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeUsuario_lbl;
    private javax.swing.JLabel ola_lbl;
    private javax.swing.JTextArea pesquisa_txt;
    // End of variables declaration//GEN-END:variables
}
